services:
  postgres:
    image: postgres:15
    container_name: postgres-naturegift
    environment:
      POSTGRES_USER: naturegift
      POSTGRES_PASSWORD: naturegift
      POSTGRES_DB: naturegift-store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nature-gift-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U naturegift -d naturegift-store"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: {}

networks:
  nature-gift-network:
    driver: bridge
