version: "3"
services:
  nature_gift_admin:
    restart: unless-stopped
    image: node:18-alpine
    ports:
      - "8004:3000"
      - "8005:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run serve"

  mongodb:
    restart: unless-stopped
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: store
  
  bidnamiMongo:
    image: bitnami/mongodb:5.0.10-debian-11-r3
    container_name: store-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_DATABASE=store
    volumes:
      - "./data:/data/db"


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/store?authSource=admin
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb_data:
  node_modules:
